### ISSUE TITLE
Variables Within Sections Won't Render

### ISSUE THREAD

**Issue by MountainCode** [StubbleOrg/Stubble.Extensions.JsonNet#3]
`JObject` properties will not render with a mustache variable inside a section.

Example:
```json
{ "foo": { "bar": "foobar" } }
```

```mustache
{{#foo}}{{bar}}{{/foo}}
```
Will render an empty string.

It looks like the problem is that a `JProperty` is returned when getting the `foo` value, but `JProperty` doesn't inherit `JObject` so the `JsonNet.ValueGetters` are not used.

I think I've fixed the issue and will submit a pull request.

**Comment by MountainCode** [comment]
PR #4

**Comment by Romanx** [comment]
Hi there,

Thanks for the contribution. I'll look at getting this merged and fixing the failing linux build later today.

**Comment by Romanx** [comment]
Thanks for your contibution. This has been merged and released in version v1.1.5

Thanks!
